import LinkedList from "./linkedList";

const linkedList = new LinkedList();
linkedList.append("test");
linkedList.append("test2");
linkedList.append("test3");
linkedList.append("test4");
linkedList.prepend("test5");
linkedList.prepend("test6");
console.log(linkedList.size());
console.log(linkedList.getHead());
console.log(linkedList.getTail());
console.log(linkedList.atIndex(0));
console.log(linkedList.atIndex(2));
console.log(linkedList.atIndex(5));
console.log(linkedList.atIndex(7));
linkedList.pop();
console.log(linkedList.getTail());
console.log(linkedList.contains("test2"));
console.log(linkedList.contains("test5"));
console.log(linkedList.contains("test4"));
console.log(linkedList.find("test2"));
console.log(linkedList.find("test5"));
console.log(linkedList.find("test4"));
console.log(linkedList.toString());
linkedList.insertAt("test7", 3);
console.log(linkedList.toString());
linkedList.removeAt(1);
console.log(linkedList.toString());